default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_520_ci
  reconnect: false
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: valetbike_development
  username: nikki
  password: rootroot
  host: 127.0.0.1

test:
  <<: *default
  database: valetbike_test
  username: root
  password: rootroot

production:
  <<: *default
  database: valetbike_production
  username: root
  password: rootroot
 